feature/1.19.0
ConsumerDataStandardsAustralia/java-artefacts pull request #154
Opened 2022-10-06 22:39 UTC by abeheron1

PR to merge java artefacts 1.19 CDS changes to master.

2022-10-11 07:06 UTC, vadkor requested changes

2022-10-11 07:18 UTC, abeheron1 commented on client-cli/keystore/keystore.jwks
> -}
Didn't intend, likely just whitespace while looking at it. Will undo.

2022-10-11 22:34 UTC, abeheron1 commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyAccountV2.java
> +    @Transient
Yes, I didn't like it either. But short of actually having any plans to map in the json files. I'll see if I can somehow put some sample data and thus remove the transient.

2022-10-13 01:29 UTC, abeheron1 commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyAccountV1.java
> +    @Transient
Fixed.

2022-10-13 01:39 UTC, abeheron1 commented on client-cli/src/main/java/au/org/consumerdatastandards/client/cli/energy/EnergyAccounts.java
> +        ApiResponse<EnergyAccountListResponse<EnergyAccountV1>> response = result.getResponse();
Should really be EnergyAccountBase, corrected.

2022-10-13 11:49 UTC, vadkor requested changes

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/util/CdsDataLoader.java
> +        //load("payloads/energy/accounts", energyAccountV1Repository, EnergyAccountV2.class);
Forgotten to remove this line?

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyAccountDetailAuthorisedContacts.java
> +@Table(name = "AuthorisedContact")
Maybe better EnergyAuthorisedContact?

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyPlanContract.java
> +@Table(name = "EnergyPlanContract")
No need for this line

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyAccountPlans.java
> +@Table(name = "EnergyAccountPlan")
No need for this line

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyAccountPlanOverview.java
> +@Table(name = "PlanOverview")
Better: EnergyPlanOverview - other industries will have Plans

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyAccountDetailPlans.java
> +@Table(name="DetailPlan")
EnergyDetailPlan?

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyPlanContractDiscounts.java
> +@Table(name="ContractDiscount")
EnergyContractDiscount?

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyPlanContractEligibility.java
> +@Table(name="ContractEligibility")
EnergyContractEligibility?

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyPlanContractFees.java
> +@Table(name="ContractFee")
EnergyContractFee?

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyPlanContractIncentives.java
> +@Table(name="ContractIncentive")
EnergyContractIncentive?

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyPlanContractTariffPeriod.java
> +@Table(name="TariffPeriod")
EnergyTariffPeriod?

2022-10-13 11:49 UTC, vadkor commented on client/src/main/java/au/org/consumerdatastandards/client/api/ProtectedAPI.java
> +        headers.put("x-fapi-auth-date", DateTimeFormatter.RFC_1123_DATE_TIME.format(ZonedDateTime.now(ZoneOffset.UTC)));
Thanks for the fix!

2022-10-13 11:49 UTC, vadkor commented on client/src/main/java/au/org/consumerdatastandards/client/api/energy/EnergyAccountsAPI.java
> +
?

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/api/energy/EnergyApiController.java
> +        data.setAccounts(energyAccountPage.getContent());
One line two many?

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyAccountDetailResponse.java
>      @JsonProperty("data")
We also remove unneeded @JsonProperty

2022-10-13 11:49 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/service/energy/EnergyService.java
> +import au.org.consumerdatastandards.holder.repository.energy.*;
Wildcard import

2022-10-13 11:53 UTC, vadkor commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/api/energy/EnergyApiController.java
> +        data.setAccounts(energyAccountPage.getContent());
Nope. All good.

2022-10-13 21:38 UTC, abeheron1 commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/util/CdsDataLoader.java
> +        //load("payloads/energy/accounts", energyAccountV1Repository, EnergyAccountV2.class);
yes.

2022-10-13 22:14 UTC, abeheron1 commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyAccountDetailResponse.java
>          date = "2022-01-11T14:03:27.755+11:00[Australia/Sydney]")
I didn't add those, were from before

2022-10-13 22:15 UTC, abeheron1 commented on data-holder/src/main/java/au/org/consumerdatastandards/holder/model/energy/EnergyAccountDetailResponse.java
>          date = "2022-01-11T14:03:27.755+11:00[Australia/Sydney]")
Oh I see what you mean, once edited manually to remove.

2022-10-14 01:43 UTC, merged